onroad_payload = {
    "form": {
        "output": "Emissions",
        "regionType": "Sub-Area",
        "modelVersion": "emfac2021",
        "modelVersionNumber": {"label": "v1.0.2", "value": "v102_byspeed"},
        "modelVersionNumberLabel": "v1.0.2",
        "modelVersionNumberValue": "v102_byspeed",
        "region": [{"id": "59", "name": "Los Angeles (SC)"}],
        "calendarYear": [
            2000,
            2001,
            2002,
            2003,
            2004,
            2005,
            2006,
            2007,
            2008,
            2009,
            2010,
            2011,
            2012,
            2013,
            2014,
            2015,
            2016,
            2017,
            2018,
            2019,
            2020,
            2021,
            2022,
            2023,
            2024,
            2025,
            2026,
            2027,
            2028,
            2029,
            2030,
            2031,
            2032,
            2033,
            2034,
            2035,
            2036,
            2037,
            2038,
            2039,
            2040,
            2041,
            2042,
            2043,
            2044,
            2045,
            2046,
            2047,
            2048,
            2049,
            2050,
        ],
        "season": "Annual",
        "scenario": "exh",
        "vehicleCategoryMode": "emfac202x",
        "vehicleCategory": [
            "LDA",
            "LDT1",
            "LDT2",
            "MDV",
            "MCY",
            "MH",
            "LHD1",
            "LHD2",
            "T6 Public Class 4",
            "T6 Public Class 5",
            "T6 Public Class 6",
            "T6 Public Class 7",
            "T6 Utility Class 5",
            "T6 Utility Class 6",
            "T6 Utility Class 7",
            "T6 Instate Tractor Class 6",
            "T6 Instate Delivery Class 4",
            "T6 Instate Delivery Class 5",
            "T6 Instate Delivery Class 6",
            "T6 Instate Other Class 4",
            "T6 Instate Other Class 5",
            "T6 Instate Other Class 6",
            "T6 Instate Tractor Class 7",
            "T6 Instate Delivery Class 7",
            "T6 Instate Other Class 7",
            "T6 CAIRP Class 4",
            "T6 CAIRP Class 5",
            "T6 CAIRP Class 6",
            "T6 CAIRP Class 7",
            "T6 OOS Class 4",
            "T6 OOS Class 5",
            "T6 OOS Class 6",
            "T6 OOS Class 7",
            "T6TS",
            "T7 Public Class 8",
            "T7 CAIRP Class 8",
            "T7 Utility Class 8",
            "T7 NNOOS Class 8",
            "T7 NOOS Class 8",
            "T7 Other Port Class 8",
            "T7 POAK Class 8",
            "T7 POLA Class 8",
            "T7 Single Concrete/Transit Mix Class 8",
            "T7 Single Dump Class 8",
            "T7 Single Other Class 8",
            "T7 Tractor Class 8",
            "T7 SWCV Class 8",
            "T7IS",
            "PTO",
            "UBUS",
            "SBUS",
            "Motor Coach",
            "OBUS",
            "All Other Buses",
        ],
        "vehicleCategoryOffroadSector": [],
        "modelYearMode": "Aggregate",
        "modelYear": [
            1965,
            1966,
            1967,
            1968,
            1969,
            1970,
            1971,
            1972,
            1973,
            1974,
            1975,
            1976,
            1977,
            1978,
            1979,
            1980,
            1981,
            1982,
            1983,
            1984,
            1985,
            1986,
            1987,
            1988,
            1989,
            1990,
            1991,
            1992,
            1993,
            1994,
            1995,
            1996,
            1997,
            1998,
            1999,
            2000,
            2001,
            2002,
            2003,
            2004,
            2005,
            2006,
            2007,
            2008,
            2009,
            2010,
            2011,
            2012,
            2013,
            2014,
            2015,
            2016,
            2017,
            2018,
            2019,
            2020,
            2021,
            2022,
            2023,
            2024,
            2025,
            2026,
            2027,
            2028,
            2029,
            2030,
            2031,
            2032,
            2033,
            2034,
            2035,
            2036,
            2037,
            2038,
            2039,
            2040,
            2041,
            2042,
            2043,
            2044,
            2045,
            2046,
            2047,
            2048,
            2049,
            2050,
            2051,
        ],
        "modelYearStart": 1965,
        "modelYearEnd": 2051,
        "modelYearStartSelected": 1965,
        "modelYearEndSelected": 2051,
        "speedMode": "Aggregate",
        "speed": [
            5,
            10,
            15,
            20,
            25,
            30,
            35,
            40,
            45,
            50,
            55,
            60,
            65,
            70,
            75,
            80,
            85,
            90,
        ],
        "fuel": [
            {"id": 1, "name": "Gasoline"},
            {"id": 2, "name": "Diesel"},
            {"id": 3, "name": "Electricity"},
            {"id": 4, "name": "Natural Gas"},
            {"id": 5, "name": "Plug-in Hybrid"},
        ],
        "unit": "year",
        "outputCols": {
            "activities": [
                "Population",
                "Total VMT",
                "CVMT",
                "EVMT",
                "Trips",
                "Energy Consumption",
                "Fuel Consumption",
            ],
            "pollutants": [
                "NOx",
                "PM2.5",
                "PM10",
                "CO2",
                "CH4",
                "N2O",
                "ROG",
                "TOG",
                "CO",
                "SOx",
                "NH3",
            ],
            "processes": [
                "RUNEX",
                "IDLEX",
                "STREX",
                "TOTEX",
                "PMTW",
                "PMBW",
                "TOTAL",
                "DIURN",
                "HOTSOAK",
                "RUNLOSS",
            ],
            "tableColumns": [
                {"name": "No", "label": "No", "field": "No", "sortable": "true"},
                {
                    "name": "Calendar Year",
                    "label": "Calendar Year",
                    "field": "Calendar Year",
                    "sortable": "true",
                },
                {
                    "name": "Vehicle Category",
                    "label": "Vehicle Category",
                    "align": "left",
                    "field": "Vehicle Category",
                    "sortable": "true",
                },
                {
                    "name": "Fuel",
                    "label": "Fuel",
                    "align": "left",
                    "field": "Fuel",
                    "sortable": "true",
                },
                {
                    "name": "Population",
                    "label": "Population",
                    "field": "Population",
                    "sortable": "true",
                },
                {
                    "name": "Total VMT",
                    "label": "Total VMT",
                    "field": "Total VMT",
                    "sortable": "true",
                },
                {"name": "CVMT", "label": "CVMT", "field": "CVMT", "sortable": "true"},
                {"name": "EVMT", "label": "EVMT", "field": "EVMT", "sortable": "true"},
                {
                    "name": "Trips",
                    "label": "Trips",
                    "field": "Trips",
                    "sortable": "true",
                },
                {
                    "name": "Energy Consumption",
                    "label": "Energy Consumption",
                    "field": "Energy Consumption",
                    "sortable": "true",
                },
                {
                    "name": "NOx_RUNEX",
                    "label": "NOx_RUNEX",
                    "field": "NOx_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "NOx_IDLEX",
                    "label": "NOx_IDLEX",
                    "field": "NOx_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "NOx_STREX",
                    "label": "NOx_STREX",
                    "field": "NOx_STREX",
                    "sortable": "true",
                },
                {
                    "name": "NOx_TOTEX",
                    "label": "NOx_TOTEX",
                    "field": "NOx_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_RUNEX",
                    "label": "PM2.5_RUNEX",
                    "field": "PM2.5_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_IDLEX",
                    "label": "PM2.5_IDLEX",
                    "field": "PM2.5_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_STREX",
                    "label": "PM2.5_STREX",
                    "field": "PM2.5_STREX",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_TOTEX",
                    "label": "PM2.5_TOTEX",
                    "field": "PM2.5_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_PMTW",
                    "label": "PM2.5_PMTW",
                    "field": "PM2.5_PMTW",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_PMBW",
                    "label": "PM2.5_PMBW",
                    "field": "PM2.5_PMBW",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_TOTAL",
                    "label": "PM2.5_TOTAL",
                    "field": "PM2.5_TOTAL",
                    "sortable": "true",
                },
                {
                    "name": "PM10_RUNEX",
                    "label": "PM10_RUNEX",
                    "field": "PM10_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "PM10_IDLEX",
                    "label": "PM10_IDLEX",
                    "field": "PM10_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "PM10_STREX",
                    "label": "PM10_STREX",
                    "field": "PM10_STREX",
                    "sortable": "true",
                },
                {
                    "name": "PM10_TOTEX",
                    "label": "PM10_TOTEX",
                    "field": "PM10_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "PM10_PMTW",
                    "label": "PM10_PMTW",
                    "field": "PM10_PMTW",
                    "sortable": "true",
                },
                {
                    "name": "PM10_PMBW",
                    "label": "PM10_PMBW",
                    "field": "PM10_PMBW",
                    "sortable": "true",
                },
                {
                    "name": "PM10_TOTAL",
                    "label": "PM10_TOTAL",
                    "field": "PM10_TOTAL",
                    "sortable": "true",
                },
                {
                    "name": "CO2_RUNEX",
                    "label": "CO2_RUNEX",
                    "field": "CO2_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "CO2_IDLEX",
                    "label": "CO2_IDLEX",
                    "field": "CO2_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "CO2_STREX",
                    "label": "CO2_STREX",
                    "field": "CO2_STREX",
                    "sortable": "true",
                },
                {
                    "name": "CO2_TOTEX",
                    "label": "CO2_TOTEX",
                    "field": "CO2_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "CH4_RUNEX",
                    "label": "CH4_RUNEX",
                    "field": "CH4_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "CH4_IDLEX",
                    "label": "CH4_IDLEX",
                    "field": "CH4_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "CH4_STREX",
                    "label": "CH4_STREX",
                    "field": "CH4_STREX",
                    "sortable": "true",
                },
                {
                    "name": "CH4_TOTEX",
                    "label": "CH4_TOTEX",
                    "field": "CH4_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "N2O_RUNEX",
                    "label": "N2O_RUNEX",
                    "field": "N2O_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "N2O_IDLEX",
                    "label": "N2O_IDLEX",
                    "field": "N2O_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "N2O_STREX",
                    "label": "N2O_STREX",
                    "field": "N2O_STREX",
                    "sortable": "true",
                },
                {
                    "name": "N2O_TOTEX",
                    "label": "N2O_TOTEX",
                    "field": "N2O_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "ROG_RUNEX",
                    "label": "ROG_RUNEX",
                    "field": "ROG_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "ROG_IDLEX",
                    "label": "ROG_IDLEX",
                    "field": "ROG_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "ROG_STREX",
                    "label": "ROG_STREX",
                    "field": "ROG_STREX",
                    "sortable": "true",
                },
                {
                    "name": "ROG_TOTEX",
                    "label": "ROG_TOTEX",
                    "field": "ROG_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "ROG_DIURN",
                    "label": "ROG_DIURN",
                    "field": "ROG_DIURN",
                    "sortable": "true",
                },
                {
                    "name": "ROG_HOTSOAK",
                    "label": "ROG_HOTSOAK",
                    "field": "ROG_HOTSOAK",
                    "sortable": "true",
                },
                {
                    "name": "ROG_RUNLOSS",
                    "label": "ROG_RUNLOSS",
                    "field": "ROG_RUNLOSS",
                    "sortable": "true",
                },
                {
                    "name": "ROG_TOTAL",
                    "label": "ROG_TOTAL",
                    "field": "ROG_TOTAL",
                    "sortable": "true",
                },
                {
                    "name": "TOG_RUNEX",
                    "label": "TOG_RUNEX",
                    "field": "TOG_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "TOG_IDLEX",
                    "label": "TOG_IDLEX",
                    "field": "TOG_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "TOG_STREX",
                    "label": "TOG_STREX",
                    "field": "TOG_STREX",
                    "sortable": "true",
                },
                {
                    "name": "TOG_TOTEX",
                    "label": "TOG_TOTEX",
                    "field": "TOG_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "TOG_DIURN",
                    "label": "TOG_DIURN",
                    "field": "TOG_DIURN",
                    "sortable": "true",
                },
                {
                    "name": "TOG_HOTSOAK",
                    "label": "TOG_HOTSOAK",
                    "field": "TOG_HOTSOAK",
                    "sortable": "true",
                },
                {
                    "name": "TOG_RUNLOSS",
                    "label": "TOG_RUNLOSS",
                    "field": "TOG_RUNLOSS",
                    "sortable": "true",
                },
                {
                    "name": "TOG_TOTAL",
                    "label": "TOG_TOTAL",
                    "field": "TOG_TOTAL",
                    "sortable": "true",
                },
                {
                    "name": "CO_RUNEX",
                    "label": "CO_RUNEX",
                    "field": "CO_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "CO_IDLEX",
                    "label": "CO_IDLEX",
                    "field": "CO_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "CO_STREX",
                    "label": "CO_STREX",
                    "field": "CO_STREX",
                    "sortable": "true",
                },
                {
                    "name": "CO_TOTEX",
                    "label": "CO_TOTEX",
                    "field": "CO_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "SOx_RUNEX",
                    "label": "SOx_RUNEX",
                    "field": "SOx_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "SOx_IDLEX",
                    "label": "SOx_IDLEX",
                    "field": "SOx_IDLEX",
                    "sortable": "true",
                },
                {
                    "name": "SOx_STREX",
                    "label": "SOx_STREX",
                    "field": "SOx_STREX",
                    "sortable": "true",
                },
                {
                    "name": "SOx_TOTEX",
                    "label": "SOx_TOTEX",
                    "field": "SOx_TOTEX",
                    "sortable": "true",
                },
                {
                    "name": "NH3_RUNEX",
                    "label": "NH3_RUNEX",
                    "field": "NH3_RUNEX",
                    "sortable": "true",
                },
                {
                    "name": "Fuel Consumption",
                    "label": "Fuel Consumption",
                    "field": "Fuel Consumption",
                    "sortable": "true",
                },
            ],
            "visibleCols": [
                "No",
                "Calendar Year",
                "Vehicle Category",
                "Fuel",
                "Population",
                "Total VMT",
                "CVMT",
                "EVMT",
                "Trips",
                "Energy Consumption",
                "NOx_RUNEX",
                "NOx_IDLEX",
                "NOx_STREX",
                "NOx_TOTEX",
                "PM2.5_RUNEX",
                "PM2.5_IDLEX",
                "PM2.5_STREX",
                "PM2.5_TOTEX",
                "PM2.5_PMTW",
                "PM2.5_PMBW",
                "PM2.5_TOTAL",
                "PM10_RUNEX",
                "PM10_IDLEX",
                "PM10_STREX",
                "PM10_TOTEX",
                "PM10_PMTW",
                "PM10_PMBW",
                "PM10_TOTAL",
                "CO2_RUNEX",
                "CO2_IDLEX",
                "CO2_STREX",
                "CO2_TOTEX",
                "CH4_RUNEX",
                "CH4_IDLEX",
                "CH4_STREX",
                "CH4_TOTEX",
                "N2O_RUNEX",
                "N2O_IDLEX",
                "N2O_STREX",
                "N2O_TOTEX",
                "ROG_RUNEX",
                "ROG_IDLEX",
                "ROG_STREX",
                "ROG_TOTEX",
                "ROG_DIURN",
                "ROG_HOTSOAK",
                "ROG_RUNLOSS",
                "ROG_TOTAL",
                "TOG_RUNEX",
                "TOG_IDLEX",
                "TOG_STREX",
                "TOG_TOTEX",
                "TOG_DIURN",
                "TOG_HOTSOAK",
                "TOG_RUNLOSS",
                "TOG_TOTAL",
                "CO_RUNEX",
                "CO_IDLEX",
                "CO_STREX",
                "CO_TOTEX",
                "SOx_RUNEX",
                "SOx_IDLEX",
                "SOx_STREX",
                "SOx_TOTEX",
                "NH3_RUNEX",
                "Fuel Consumption",
            ],
            "allCols": [
                "No",
                "Calendar Year",
                "Vehicle Category",
                "Fuel",
                "Population",
                "Total VMT",
                "CVMT",
                "EVMT",
                "Trips",
                "Energy Consumption",
                "NOx_RUNEX",
                "NOx_IDLEX",
                "NOx_STREX",
                "NOx_TOTEX",
                "PM2.5_RUNEX",
                "PM2.5_IDLEX",
                "PM2.5_STREX",
                "PM2.5_TOTEX",
                "PM2.5_PMTW",
                "PM2.5_PMBW",
                "PM2.5_TOTAL",
                "PM10_RUNEX",
                "PM10_IDLEX",
                "PM10_STREX",
                "PM10_TOTEX",
                "PM10_PMTW",
                "PM10_PMBW",
                "PM10_TOTAL",
                "CO2_RUNEX",
                "CO2_IDLEX",
                "CO2_STREX",
                "CO2_TOTEX",
                "CH4_RUNEX",
                "CH4_IDLEX",
                "CH4_STREX",
                "CH4_TOTEX",
                "N2O_RUNEX",
                "N2O_IDLEX",
                "N2O_STREX",
                "N2O_TOTEX",
                "ROG_RUNEX",
                "ROG_IDLEX",
                "ROG_STREX",
                "ROG_TOTEX",
                "ROG_DIURN",
                "ROG_HOTSOAK",
                "ROG_RUNLOSS",
                "ROG_TOTAL",
                "TOG_RUNEX",
                "TOG_IDLEX",
                "TOG_STREX",
                "TOG_TOTEX",
                "TOG_DIURN",
                "TOG_HOTSOAK",
                "TOG_RUNLOSS",
                "TOG_TOTAL",
                "CO_RUNEX",
                "CO_IDLEX",
                "CO_STREX",
                "CO_TOTEX",
                "SOx_RUNEX",
                "SOx_IDLEX",
                "SOx_STREX",
                "SOx_TOTEX",
                "NH3_RUNEX",
                "Fuel Consumption",
            ],
        },
        "showMap": "true",
        "offroadTable": "null",
        "version": "2022-04-29",
        "calendarYearMode": "Select",
        "calendarYearStartSelected": 2000,
        "calendarYearEndSelected": 2050,
        "calendarYearStart": 2000,
        "calendarYearEnd": 2050,
        "vehicleCategoryAll": "true",
        "modelYearAll": "true",
        "speedAll": "true",
        "fuelAll": "true",
        "output_format": "json",
    },
    "hash": "15de19c9f69f14de472eff0aaf487b1bfb411f06",
}

offroad_payload = {
    "form": {
        "output": "Offroad",
        "regionType": "Sub-Area",
        "modelVersion": "emfac2021",
        "modelVersionNumber": {"label": "v1.0.2", "value": "v102_byspeed"},
        "modelVersionNumberLabel": "v1.0.2",
        "modelVersionNumberValue": "v102_byspeed",
        "region": [{"id": "59", "name": "Los Angeles (SC)"}],
        "calendarYear": [
            2015,
            2016,
            2017,
            2018,
            2019,
            2020,
            2021,
            2022,
            2023,
            2024,
            2025,
            2026,
            2027,
            2028,
            2029,
            2030,
            2031,
            2032,
            2033,
            2034,
            2035,
            2036,
            2037,
            2038,
            2039,
            2040,
            2041,
            2042,
            2043,
            2044,
            2045,
            2046,
            2047,
            2048,
            2049,
            2050,
        ],
        "season": "Annual",
        "scenario": "exh",
        "vehicleCategoryMode": "emfac202x",
        "vehicleCategory": [
            "Agricultural - Agricultural Tractors",
            "Agricultural - ATVs",
            "Agricultural - Bale Wagons (Self Propelled)",
            "Agricultural - Balers (Self Propelled)",
            "Agricultural - Combine Harvesters",
            "Agricultural - Construction Equipment",
            "Agricultural - Cotton Pickers",
            "Agricultural - Forage & Silage Harvesters",
            "Agricultural - Forklifts",
            "Agricultural - Hay Squeeze/Stack Retriever",
            "Agricultural - Nut Harvester",
            "Agricultural - Other",
            "Agricultural - Other Harvesters",
            "Agricultural - Sprayers/Spray Rigs",
            "Agricultural - Swathers/Windrowers/Hay Conditioners",
            "Airport Ground Support - A/C Tug Narrow Body",
            "Airport Ground Support - A/C Tug Wide Body",
            "Airport Ground Support - Baggage Tug",
            "Airport Ground Support - Belt Loader",
            "Airport Ground Support - Bobtail",
            "Airport Ground Support - Cargo Loader",
            "Airport Ground Support - Cargo Tractor",
            "Airport Ground Support - Forklift",
            "Airport Ground Support - Lift",
            "Airport Ground Support - Misc - A/C Tug  Narrow Body",
            "Airport Ground Support - Misc - A/C Tug  Wide Body",
            "Airport Ground Support - Misc - Air Conditioner",
            "Airport Ground Support - Misc - Air Start Unit",
            "Airport Ground Support - Misc - Baggage Tug",
            "Airport Ground Support - Misc - Belt Loader",
            "Airport Ground Support - Misc - Bobtail",
            "Airport Ground Support - Misc - Cargo Loader",
            "Airport Ground Support - Misc - Cargo Tractor",
            "Airport Ground Support - Misc - Cart",
            "Airport Ground Support - Misc - Catering Truck",
            "Airport Ground Support - Misc - Compressor",
            "Airport Ground Support - Misc - Deicer",
            "Airport Ground Support - Misc - Forklift",
            "Airport Ground Support - Misc - Fuel Truck",
            "Airport Ground Support - Misc - Generator",
            "Airport Ground Support - Misc - Ground Power Unit",
            "Airport Ground Support - Misc - Hydrant Truck",
            "Airport Ground Support - Misc - Lav Cart",
            "Airport Ground Support - Misc - Lav Truck",
            "Airport Ground Support - Misc - Lift",
            "Airport Ground Support - Misc - Maint. Truck",
            "Airport Ground Support - Misc - Other",
            "Airport Ground Support - Misc - Other",
            "Airport Ground Support - Misc - Passenger Stand",
            "Airport Ground Support - Misc - Service Truck",
            "Airport Ground Support - Misc - Sweeper",
            "Airport Ground Support - Misc - Water Truck",
            "Airport Ground Support - Other",
            "Airport Ground Support - Passenger Stand",
            "Cargo Handling Equipment - Port AGV",
            "Cargo Handling Equipment - Port Compactor (Portable)",
            "Cargo Handling Equipment - Port Construction Equipment",
            "Cargo Handling Equipment - Port Container Handling Equipment",
            "Cargo Handling Equipment - Port Crane",
            "Cargo Handling Equipment - Port Electric Pallet Jack",
            "Cargo Handling Equipment - Port Excavator",
            "Cargo Handling Equipment - Port Forklift",
            "Cargo Handling Equipment - Port Lift",
            "Cargo Handling Equipment - Port Other",
            "Cargo Handling Equipment - Port Other General Industrial Equipment",
            "Cargo Handling Equipment - Port Rail Car Mover",
            "Cargo Handling Equipment - Port Rtg Crane",
            "Cargo Handling Equipment - Port RTG Crane",
            "Cargo Handling Equipment - Port Skid Steer Loaders",
            "Cargo Handling Equipment - Port STS Crane",
            "Cargo Handling Equipment - Port Tractor",
            "Cargo Handling Equipment - Port Tractors/Loaders/Backhoes",
            "Cargo Handling Equipment - Port Truck",
            "Cargo Handling Equipment - Port Yard Tractor",
            "Cargo Handling Equipment - Port Yard Truck",
            "Cargo Handling Equipment - Rail AGV",
            "Cargo Handling Equipment - Rail Compactor (Portable)",
            "Cargo Handling Equipment - Rail Construction Equipment",
            "Cargo Handling Equipment - Rail Container Handling Equipment",
            "Cargo Handling Equipment - Rail Crane",
            "Cargo Handling Equipment - Rail Electric Pallet Jack",
            "Cargo Handling Equipment - Rail Excavator",
            "Cargo Handling Equipment - Rail Forklift",
            "Cargo Handling Equipment - Rail Lift",
            "Cargo Handling Equipment - Rail Other",
            "Cargo Handling Equipment - Rail Other General Industrial Equipment",
            "Cargo Handling Equipment - Rail Rail Car Mover",
            "Cargo Handling Equipment - Rail Rtg Crane",
            "Cargo Handling Equipment - Rail RTG Crane",
            "Cargo Handling Equipment - Rail Skid Steer Loaders",
            "Cargo Handling Equipment - Rail STS Crane",
            "Cargo Handling Equipment - Rail Tractor",
            "Cargo Handling Equipment - Rail Tractors/Loaders/Backhoes",
            "Cargo Handling Equipment - Rail Truck",
            "Cargo Handling Equipment - Rail Yard Tractor",
            "Cargo Handling Equipment - Rail Yard Truck",
            "Commercial Harbor Craft - AE - Barge-ATB",
            "Commercial Harbor Craft - AE - Barge-Bunker",
            "Commercial Harbor Craft - AE - Barge-Other",
            "Commercial Harbor Craft - AE - Barge-Towed Petrochemical",
            "Commercial Harbor Craft - AE - Commercial Fishing",
            "Commercial Harbor Craft - AE - Commercial Passenger Fishing",
            "Commercial Harbor Craft - AE - Crew/Supply",
            "Commercial Harbor Craft - AE - Dredge",
            "Commercial Harbor Craft - AE - Excursion",
            "Commercial Harbor Craft - AE - Ferry-Catamaran",
            "Commercial Harbor Craft - AE - Ferry-Monohull",
            "Commercial Harbor Craft - AE - Ferry-Short Run",
            "Commercial Harbor Craft - AE - Pilot Boat",
            "Commercial Harbor Craft - AE - Research Boat",
            "Commercial Harbor Craft - AE - Tugboat-ATB",
            "Commercial Harbor Craft - AE - Tugboat-Escort/Ship Assist",
            "Commercial Harbor Craft - AE - Tugboat-Push/Tow",
            "Commercial Harbor Craft - AE - Work Boat",
            "Commercial Harbor Craft - AE - Other",
            "Commercial Harbor Craft - ME - Commercial Fishing",
            "Commercial Harbor Craft - ME - Commercial Passenger Fishing",
            "Commercial Harbor Craft - ME - Crew/Supply",
            "Commercial Harbor Craft - ME - Dredge",
            "Commercial Harbor Craft - ME - Excursion",
            "Commercial Harbor Craft - ME - Ferry-Catamaran",
            "Commercial Harbor Craft - ME - Ferry-Monohull",
            "Commercial Harbor Craft - ME - Ferry-Short Run",
            "Commercial Harbor Craft - ME - Pilot Boat",
            "Commercial Harbor Craft - ME - Research Boat",
            "Commercial Harbor Craft - ME - Tugboat-ATB",
            "Commercial Harbor Craft - ME - Tugboat-Escort/Ship Assist",
            "Commercial Harbor Craft - ME - Tugboat-Push/Tow",
            "Commercial Harbor Craft - ME - Work Boat",
            "Commercial Harbor Craft - ME - Other",
            "Construction and Mining - Bore/Drill Rigs",
            "Construction and Mining - Cranes",
            "Construction and Mining - Crawler Tractors",
            "Construction and Mining - Excavators",
            "Construction and Mining - Graders",
            "Construction and Mining - Misc - Asphalt Pavers",
            "Construction and Mining - Misc - Bore/Drill Rigs",
            "Construction and Mining - Misc - Cement And Mortar Mixers",
            "Construction and Mining - Misc - Concrete/Industrial Saws",
            "Construction and Mining - Misc - Cranes",
            "Construction and Mining - Misc - Crushing/Proc. Equipment",
            "Construction and Mining - Misc - Dumpers/Tenders",
            "Construction and Mining - Misc - Excavators",
            "Construction and Mining - Misc - Other",
            "Construction and Mining - Misc - Pavers",
            "Construction and Mining - Misc - Paving Equipment",
            "Construction and Mining - Misc - Plate Compactors",
            "Construction and Mining - Misc - Rollers",
            "Construction and Mining - Misc - Rough Terrain Forklifts",
            "Construction and Mining - Misc - Rubber Tired Loaders",
            "Construction and Mining - Misc - Signal Boards",
            "Construction and Mining - Misc - Skid Steer Loaders",
            "Construction and Mining - Misc - Surfacing Equipment",
            "Construction and Mining - Misc - Tampers/Rammers",
            "Construction and Mining - Misc - Tractors/Loaders/Backhoes",
            "Construction and Mining - Misc - Trenchers",
            "Construction and Mining - Off-Highway Tractors",
            "Construction and Mining - Off-Highway Trucks",
            "Construction and Mining - Other",
            "Construction and Mining - Pavers",
            "Construction and Mining - Paving Equipment",
            "Construction and Mining - Rollers",
            "Construction and Mining - Rough Terrain Forklifts",
            "Construction and Mining - Rubber Tired Dozers",
            "Construction and Mining - Rubber Tired Loaders",
            "Construction and Mining - Scrapers",
            "Construction and Mining - Skid Steer Loaders",
            "Construction and Mining - Surfacing Equipment",
            "Construction and Mining - Sweepers/Scrubbers",
            "Construction and Mining - Tractors/Loaders/Backhoes",
            "Construction and Mining - Trenchers",
            "Forestry - Extraction",
            "Forestry - Manufacturing",
            "Forestry - Maintenance & Construction",
            "Forestry - Misc - Chainsaws",
            "Forestry - Misc - Fellers/Bunchers",
            "Forestry - Misc - Shredders",
            "Forestry - Misc - Skidders",
            "Gas Can - Commercial",
            "Gas Can - Residential",
            "Industrial - Aerial Lifts",
            "Industrial - Forklifts",
            "Industrial - Misc - Aerial Lifts",
            "Industrial - Misc - Forklifts",
            "Industrial - Misc - Other General Industrial Equipment",
            "Industrial - Misc - Other Material Handling Equipment",
            "Industrial - Misc - Sweepers/Scrubbers",
            "Industrial - Other General Industrial Equipment",
            "Industrial - Other Material Handling Equipment",
            "Lawn and Garden - Misc - Chainsaws",
            "Lawn and Garden - Misc - Chainsaws Preempt",
            "Lawn and Garden - Misc - Chippers/Stump Grinders",
            "Lawn and Garden - Misc - Lawn Mowers",
            "Lawn and Garden - Misc - Leaf Blowers/Vacuums",
            "Lawn and Garden - Misc - Other",
            "Lawn and Garden - Misc - Rear Engine Riding Mowers",
            "Lawn and Garden - Misc - Snowblowers",
            "Lawn and Garden - Misc - Tillers",
            "Lawn and Garden - Misc - Trimmers/Edgers/Brush Cutters",
            "Lawn and Garden - Misc - Wood Splitters",
            "Light Commercial - Misc - Air Compressors",
            "Light Commercial - Misc - Gas Compressors",
            "Light Commercial - Misc - Generator Sets",
            "Light Commercial - Misc - Pressure Washers",
            "Light Commercial - Misc - Pumps",
            "Light Commercial - Misc - Welders",
            "Locomotive - Line Haul",
            "Locomotive - Passenger",
            "Locomotive - Short Line",
            "Locomotive - Switcher",
            "Military Tactical Support - Misc - A/C Unit",
            "Military Tactical Support - Misc - Aircraft Support",
            "Military Tactical Support - Misc - Cart",
            "Military Tactical Support - Misc - Communications",
            "Military Tactical Support - Misc - Compressor",
            "Military Tactical Support - Misc - Crane",
            "Military Tactical Support - Misc - Deicer",
            "Military Tactical Support - Misc - Generator",
            "Military Tactical Support - Misc - Hydraulic Unit",
            "Military Tactical Support - Misc - Lift",
            "Military Tactical Support - Misc - Light",
            "Military Tactical Support - Misc - Other Tactical Support Equipment",
            "Military Tactical Support - Misc - Pressure Washers",
            "Military Tactical Support - Misc - Pump",
            "Military Tactical Support - Misc - Start Cart",
            "Military Tactical Support - Misc - Test Stand",
            "Military Tactical Support - Misc - Welder",
            "Ocean Going Vessels - Auto Carrier",
            "Ocean Going Vessels - Bulk Cargo",
            "Ocean Going Vessels - Container",
            "Ocean Going Vessels - Cruise",
            "Ocean Going Vessels - General Cargo",
            "Ocean Going Vessels - Reefer",
            "Ocean Going Vessels - Roro",
            "Ocean Going Vessels - Tanker",
            "Ocean Going Vessels - Vessels (Other)",
            "Oil Drilling - Drill Rig (Mobile)",
            "Oil Drilling - Misc - Compressors (Workover)",
            "Oil Drilling - Misc - Generator (Drilling)",
            "Oil Drilling - Workover Rig (Mobile)",
            "Outboard Marine Tanks - Auxiliary And Sail",
            "Outboard Marine Tanks - Outboard",
            "Outboard Marine Tanks - Sail Only",
            "Pleasure Craft - Personal Water Craft",
            "Pleasure Craft - Sailboat Auxiliary Inboard Engine",
            "Pleasure Craft - Vessels W/Inboard Engines",
            "Pleasure Craft - Vessels W/Inboard Jet Engines",
            "Pleasure Craft - Vessels W/Outboard Engines",
            "Pleasure Craft - Vessels W/Sterndrive Engines",
            "Portable Equipment - Non-Rental Compressor",
            "Portable Equipment - Non-Rental Generator",
            "Portable Equipment - Non-Rental Other",
            "Portable Equipment - Non-Rental Pump",
            "Portable Equipment - Rental Compressor",
            "Portable Equipment - Rental Generator",
            "Portable Equipment - Rental Other",
            "Portable Equipment - Rental Pump",
            "Recreational - All Terrain Vehicles (Atvs) Active",
            "Recreational - Golf Carts",
            "Recreational - Minibikes",
            "Recreational - Off-Road Motorcycles Active",
            "Recreational - Snowmobiles Active",
            "Transport Refrigeration Unit - Instate Genset",
            "Transport Refrigeration Unit - Instate Trailer",
            "Transport Refrigeration Unit - Instate Truck",
            "Transport Refrigeration Unit - Instate Van",
            "Transport Refrigeration Unit - Out-Of-State Genset",
            "Transport Refrigeration Unit - Out-Of-State Trailer",
            "Transport Refrigeration Unit - Railcar TRU",
        ],
        "vehicleCategoryOffroadSector": [
            "Agricultural",
            "Airport Ground Support",
            "Cargo Handling Equipment",
            "Commercial Harbor Craft",
            "Construction and Mining",
            "Forestry",
            "Gas Can",
            "Industrial",
            "Lawn and Garden",
            "Light Commercial",
            "Locomotive",
            "Military Tactical Support",
            "Ocean Going Vessels",
            "Oil Drilling",
            "Outboard Marine Tanks",
            "Pleasure Craft",
            "Portable Equipment",
            "Recreational",
            "Transport Refrigeration Unit",
        ],
        "modelYearMode": "Aggregate",
        "modelYear": [
            1971,
            1972,
            1973,
            1974,
            1975,
            1976,
            1977,
            1978,
            1979,
            1980,
            1981,
            1982,
            1983,
            1984,
            1985,
            1986,
            1987,
            1988,
            1989,
            1990,
            1991,
            1992,
            1993,
            1994,
            1995,
            1996,
            1997,
            1998,
            1999,
            2000,
            2001,
            2002,
            2003,
            2004,
            2005,
            2006,
            2007,
            2008,
            2009,
            2010,
            2011,
            2012,
            2013,
            2014,
            2015,
            2016,
            2017,
            2018,
            2019,
            2020,
            2021,
            2022,
            2023,
            2024,
            2025,
            2026,
            2027,
            2028,
            2029,
            2030,
            2031,
            2032,
            2033,
            2034,
            2035,
            2036,
            2037,
            2038,
            2039,
            2040,
            2041,
            2042,
            2043,
            2044,
            2045,
            2046,
            2047,
            2048,
            2049,
            2050,
            2051,
        ],
        "modelYearStart": 1971,
        "modelYearEnd": 2051,
        "modelYearStartSelected": 1971,
        "modelYearEndSelected": 2051,
        "speedMode": "Aggregate",
        "speed": [2, 5, 15, 25, 50, 75, 100, 175, 300, 600, 750, 9999],
        "fuel": [
            {"id": 1, "name": "Gasoline"},
            {"id": 2, "name": "Diesel"},
            {"id": 3, "name": "Electricity"},
            {"id": 4, "name": "Natural Gas"},
            {"id": 5, "name": "Heavy Fuel Oil"},
        ],
        "unit": "year",
        "outputCols": {
            "activities": [
                "Fuel Consumption",
                "Total_Activity_hpy",
                "Total_Population",
                "Horsepower_Hours_hhpy",
            ],
            "pollutants": [
                "HC_tpd",
                "ROG_tpd",
                "TOG_tpd",
                "CO_tpd",
                "NOx_tpd",
                "CO2_tpd",
                "PM10_tpd",
                "PM2.5_tpd",
                "SOx_tpd",
                "NH3_tpd",
            ],
            "processes": [],
            "tableColumns": [
                {"name": "No", "label": "No", "field": "No", "sortable": "true"},
                {
                    "name": "Calendar Year",
                    "label": "Calendar Year",
                    "field": "Calendar Year",
                    "sortable": "true",
                },
                {
                    "name": "Vehicle Category",
                    "label": "Vehicle Category",
                    "align": "left",
                    "field": "Vehicle Category",
                    "sortable": "true",
                },
                {
                    "name": "Fuel",
                    "label": "Fuel",
                    "align": "left",
                    "field": "Fuel",
                    "sortable": "true",
                },
                {
                    "name": "HC_tpd",
                    "label": "HC",
                    "field": "HC_tpd",
                    "sortable": "true",
                },
                {
                    "name": "ROG_tpd",
                    "label": "ROG",
                    "field": "ROG_tpd",
                    "sortable": "true",
                },
                {
                    "name": "TOG_tpd",
                    "label": "TOG",
                    "field": "TOG_tpd",
                    "sortable": "true",
                },
                {
                    "name": "CO_tpd",
                    "label": "CO",
                    "field": "CO_tpd",
                    "sortable": "true",
                },
                {
                    "name": "NOx_tpd",
                    "label": "NOx",
                    "field": "NOx_tpd",
                    "sortable": "true",
                },
                {
                    "name": "CO2_tpd",
                    "label": "CO2",
                    "field": "CO2_tpd",
                    "sortable": "true",
                },
                {
                    "name": "PM10_tpd",
                    "label": "PM10",
                    "field": "PM10_tpd",
                    "sortable": "true",
                },
                {
                    "name": "PM2.5_tpd",
                    "label": "PM2.5",
                    "field": "PM2.5_tpd",
                    "sortable": "true",
                },
                {
                    "name": "SOx_tpd",
                    "label": "SOx",
                    "field": "SOx_tpd",
                    "sortable": "true",
                },
                {
                    "name": "NH3_tpd",
                    "label": "NH3",
                    "field": "NH3_tpd",
                    "sortable": "true",
                },
                {
                    "name": "Fuel Consumption",
                    "label": "Fuel Consumption",
                    "field": "Fuel Consumption",
                    "sortable": "true",
                },
                {
                    "name": "Total_Activity_hpy",
                    "label": "Total_Activity",
                    "field": "Total_Activity_hpy",
                    "sortable": "true",
                },
                {
                    "name": "Total_Population",
                    "label": "Total_Population",
                    "field": "Total_Population",
                    "sortable": "true",
                },
                {
                    "name": "Horsepower_Hours_hhpy",
                    "label": "Horsepower_Hours",
                    "field": "Horsepower_Hours_hhpy",
                    "sortable": "true",
                },
            ],
            "visibleCols": [
                "No",
                "Calendar Year",
                "Vehicle Category",
                "Fuel",
                "HC_tpd",
                "ROG_tpd",
                "TOG_tpd",
                "CO_tpd",
                "NOx_tpd",
                "CO2_tpd",
                "PM10_tpd",
                "PM2.5_tpd",
                "SOx_tpd",
                "NH3_tpd",
                "Fuel Consumption",
                "Total_Activity_hpy",
                "Total_Population",
                "Horsepower_Hours_hhpy",
            ],
            "allCols": [
                "No",
                "Calendar Year",
                "Vehicle Category",
                "Fuel",
                "HC_tpd",
                "ROG_tpd",
                "TOG_tpd",
                "CO_tpd",
                "NOx_tpd",
                "CO2_tpd",
                "PM10_tpd",
                "PM2.5_tpd",
                "SOx_tpd",
                "NH3_tpd",
                "Fuel Consumption",
                "Total_Activity_hpy",
                "Total_Population",
                "Horsepower_Hours_hhpy",
            ],
        },
        "showMap": "true",
        "offroadTable": "null",
        "version": "2022-04-29",
        "calendarYearMode": "Select",
        "calendarYearStartSelected": 2000,
        "calendarYearEndSelected": 2050,
        "calendarYearStart": 2000,
        "calendarYearEnd": 2050,
        "vehicleCategoryAll": "true",
        "modelYearAll": "true",
        "speedAll": "true",
        "fuelAll": "true",
        "output_format": "json",
    },
    "hash": "925d23b4c5deba0d2e95986d6ee42ef8b32b2c35",
}
