payload_facilities = {
    "trend": "current",
    "dataSource": "E",
    "reportingYear": "2021",
    "currentYear": "2021",
    "query": "Long Beach",
    "lowE": "-20000",
    "highE": "23000000",
    "state": "CA",
    "countyFips": "",
    "msaCode": "",
    "stateLevel": "0",
    "basin": "",
    "gases": [
        "true",
        "true",
        "true",
        "true",
        "true",
        "false",
        "true",
        "true",
        "true",
        "true",
        "true",
        "true",
    ],
    "sectors": [
        ["true"],
        ["true", "true", "true", "true", "true"],
        ["true", "true", "true", "true", "true", "true", "true", "true"],
        ["true", "true", "true", "true", "true", "true"],
        ["true"],
        ["true", "true", "true"],
        [
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
        ],
        [
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
        ],
        [
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
            "true",
        ],
    ],
    "sortOrder": "0",
    "supplierSector": 0,
    "reportingStatus": "ALL",
    "searchOptions": "11001100",
    "injectionSelection": 11,
    "emissionsType": "",
    "tribalLandId": "",
    "pageNumber": 0,
    "overlayLevel": 0,
    "visType": "list",
}
